language: java
install: true
branches:
  only:
    - master
    - /^\d+\.\d+$/
jobs:
  include:
    - stage: test
      name: "Unit tests - OracleJDK 8"
      script: mvn -B -DtestLogLevel=OFF test
      jdk: oraclejdk8
    - name: "Unit tests - OpenJDK 11"
      if: type != pull_request
      script: mvn -B -DtestLogLevel=OFF test
      jdk: openjdk11
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - stream1984@me.com
    on_success: always
    on_failure: always
